# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Dump bump
        run: |
          echo ${{ steps.bump.outputs.new_tag }}
          echo ${{ steps.bump.outputs.new_version }}
          echo ${{ steps.bump.outputs.previous_tag }}
          echo ${{ steps.bump.outputs.changelog }}

      - name: Git tag push
        run: git push --tags